version: "3"
networks:
    ezbids:

services:
    mongodb:
        container_name: brainlife_ezbids-mongodb
        image: mongo:4.4.15
        platform: linux/amd64
        volumes:
            - /data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries:
                5
        ports:
            - 27417:27017 #for local debugging
        networks:
            - ezbids

    api:
        container_name: brainlife_ezbids-api
        build: .
        platform: linux/amd64
        volumes:
            - ./api:/app/api
            - /tmp:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://api:8082/health"]
        working_dir: /app/api
        command:
            ./dev.sh
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
            BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION}
        ports:
            - 8082:8082 #localhost runs on local browser to it needs to access api via host port
        networks:
            - ezbids

    handler:
        container_name: brainlife_ezbids-handler
        build: ./handler
        platform: linux/amd64
        volumes:
            - .:/app
            - /tmp:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
            api:
                condition: service_healthy
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
        networks:
            - ezbids
        tty: true #turn on color for bids-validator output
        command: pm2 start handler.js --attach --watch --ignore-watch "ui **/node_modules"

    ui:
        container_name: brainlife_ezbids-ui
        env_file:
            - .env
        build: ./ui
        platform: linux/amd64
        volumes:
            - ./ui/src:/ui/src #don't copy node_modules which might be compiled for mac (vite won't work)
        environment:
            VITE_APIHOST: https://${SERVER_NAME}/api
            VITE_BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://ui:3000"]
        ports:
            - 3000:3000 #vite wants to be exposed on the host for HMR?
        networks:
            - ezbids

    # by default this is not enabled, need to run docker compose with --profile development to enable this service
    telemetry:
        container_name: brainlife_ezbids-telemetry
        build: ./telemetry
        platform: linux/amd64
        depends_on:
            - mongodb
        profiles: ["development"]
        ports:
            - 8000:8000 #for local debugging
        networks:
            - ezbids

    nginx:
        env_file:
            - .env
        container_name: brainlife_ezbids-nginx
        depends_on:
            - ui
            - api
        image: nginx:latest
        platform: linux/amd64
        profiles: ["development"]
        ports: 
            - 80:80
            - 443:443
        networks:
            - ezbids
        volumes: 
            - ./nginx/ssl:/etc/nginx/conf.d/ssl/
            # replace production/development depending on whether you want ssl or not
            - ./nginx/production_nginx.conf:/etc/nginx/conf.d/default.conf



